### ISSUE TITLE
[BUG] Run Program

### ISSUE THREAD

**Issue by schousda** [rivafarabi/deckboard#1097]
If i try to run a powershell script with a button, the script does not start.
Here is my button:

![image](https://github.com/rivafarabi/deckboard/assets/21222928/a9fa8146-7108-417e-b43a-c6e2397cb9b9)

This es the error shown in the log:
```
[2024-05-27 19:29:08.894] [error] runOpenFile err:  ReferenceError: exec is not defined
    at t.runOpenFile (C:\Users\user|\AppData\Local\Programs\Deckboard\resources\app.asar\dist\main\index.js:2:87317)
    at t.runCommand (C:\Users\user|\AppData\Local\Programs\Deckboard\resources\app.asar\dist\main\index.js:2:85875)
    at C:\Users\user|\AppData\Local\Programs\Deckboard\resources\app.asar\dist\main\index.js:2:175968
    at h (C:\Users\user|\AppData\Local\Programs\Deckboard\resources\app.asar\dist\main\index.js:2:157867)
    at Generator.<anonymous> (C:\Users\user|\AppData\Local\Programs\Deckboard\resources\app.asar\dist\main\index.js:2:159209)
    at Generator.next (C:\Users\user|\AppData\Local\Programs\Deckboard\resources\app.asar\dist\main\index.js:2:158296)
    at u (C:\Users\user|\AppData\Local\Programs\Deckboard\resources\app.asar\dist\main\index.js:2:163770)
    at a (C:\Users\user|\AppData\Local\Programs\Deckboard\resources\app.asar\dist\main\index.js:2:163973)
```

Windows 11
Deckboard  3.0.0-rc9.5

**Comment by rivafarabi** [comment]
Closing this since the issue has been fixed since version 3.0.0
