### ISSUE TITLE
Snap installation fails when installing sqlite3

### ISSUE THREAD

**Issue by Bus42** [rivafarabi/deckboard#1098]
**Describe the bug**
Running deckboard from the cli when installed from snap fails at the sqlite3 installation step.

**To Reproduce**
1. Install with `sudo snap install deckboard`
2. run `deckboard` in the terminal
3. See error

**Expected behavior**
The application should run without fatal errors

**Screenshots**
```cli

(deckboard:158937): Gtk-WARNING **: 17:58:55.751: Theme parsing error: gtk.css:3536:25: 'font-feature-settings' is not a valid property name
Gtk-Message: 17:58:55.763: Failed to load module "colorreload-gtk-module"
Gtk-Message: 17:58:55.763: Failed to load module "window-decorations-gtk-module"
{ appDir: '/home/greg/snap/deckboard/13/deckboard',
  os: '/home/greg/snap/deckboard/13' }
Checking for update
[17:58:57.998] [error] db:28 /snap/deckboard/13/resources/database.db is not found.
Error: Error: ENOENT: no such file or directory, open '/snap/deckboard/13/resources/app-update.yml'
(node:158937) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/snap/deckboard/13/resources/app-update.yml'
(node:158937) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:158937) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Knex: run
$ npm install sqlite3 --save
Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /run/user/1000/snap.deckboard/.org.chromium.Chromium.w8e14B)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/snap/deckboard/13/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Object.<anonymous> (/snap/deckboard/13/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/snap/deckboard/13/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:2:15)
    at Object.<anonymous> (/snap/deckboard/13/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:207:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Client_SQLite3._driver (/snap/deckboard/13/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:79:12)
    at Client_SQLite3.initializeDriver (/snap/deckboard/13/resources/app.asar/node_modules/knex/lib/client.js:254:26)
event
[17:58:58.269] [error] ext:cleanTemp Error: ENOENT: no such file or directory, scandir '/home/greg/snap/deckboard/13/deckboard/temp'
    at Object.readdirSync (fs.js:764:3)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:641:39)
    at /snap/deckboard/13/resources/app.asar/dist/main/index.js:1:21961
    at Generator.next (<anonymous>)
    at o (/snap/deckboard/13/resources/app.asar/dist/main/index.js:1:6701)
    at /snap/deckboard/13/resources/app.asar/dist/main/index.js:1:6797
    at process._tickCallback (internal/process/next_tick.js:68:7)

[17:58:58.279] [info] Connected USB Device []
Unhandled rejection TypeError: Cannot read property 'Database' of undefined
    at /snap/deckboard/13/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:106:33
    at Promise._execute (/snap/deckboard/13/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/snap/deckboard/13/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/snap/deckboard/13/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/promise.js:103:10)
    at Client_SQLite3.acquireRawConnection (/snap/deckboard/13/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:105:12)
    at create (/snap/deckboard/13/resources/app.asar/node_modules/knex/lib/client.js:283:23)
    at utils_1.tryPromise (/snap/deckboard/13/resources/app.asar/node_modules/tarn/lib/Pool.js:315:34)
    at Object.tryPromise (/snap/deckboard/13/resources/app.asar/node_modules/tarn/lib/utils.js:53:24)
    at Promise (/snap/deckboard/13/resources/app.asar/node_modules/tarn/lib/Pool.js:315:17)
    at new Promise (<anonymous>)
    at callbackOrPromise (/snap/deckboard/13/resources/app.asar/node_modules/tarn/lib/Pool.js:306:12)
    at Pool._create (/snap/deckboard/13/resources/app.asar/node_modules/tarn/lib/Pool.js:236:9)
    at Pool._doCreate (/snap/deckboard/13/resources/app.asar/node_modules/tarn/lib/Pool.js:208:36)
    at Pool._tryAcquireOrCreate (/snap/deckboard/13/resources/app.asar/node_modules/tarn/lib/Pool.js:159:18)
    at Pool.acquire (/snap/deckboard/13/resources/app.asar/node_modules/tarn/lib/Pool.js:85:14)
    at /snap/deckboard/13/resources/app.asar/node_modules/knex/lib/client.js:336:26
    at tryCatcher (/snap/deckboard/13/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/snap/deckboard/13/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/method.js:39:29)
    at Client_SQLite3.acquireConnection (/snap/deckboard/13/resources/app.asar/node_modules/knex/lib/client.js:335:34)
    at Runner.ensureConnection (/snap/deckboard/13/resources/app.asar/node_modules/knex/lib/runner.js:233:24)
    at Runner.run (/snap/deckboard/13/resources/app.asar/node_modules/knex/lib/runner.js:47:42)
    at Builder.Target.then (/snap/deckboard/13/resources/app.asar/node_modules/knex/lib/interface.js:39:43)
    at t.default.connectDatabase (/snap/deckboard/13/resources/app.asar/dist/main/index.js:1:171719)
    at u.default.copyFile.e (/snap/deckboard/13/resources/app.asar/dist/main/index.js:1:179435)
    at /snap/deckboard/13/resources/app.asar/dist/main/index.js:1:2869
    at FSReqWrap.oncomplete (fs.js:141:20)
```

**Server App (please complete the following information):**
 - OS: 
```cli
           `.:/ossyyyysso/:.               greg@studio42 
        .:oyyyyyyyyyyyyyyyyyyo:`           ------------- 
      -oyyyyyyyodMMyyyyyyyysyyyyo-         OS: Kubuntu 24.04 LTS x86_64 
    -syyyyyyyyyydMMyoyyyydmMMyyyyys-       Host: B550 Phantom Gaming 4 
   oyyysdMysyyyydMMMMMMMMMMMMMyyyyyyyo     Kernel: 6.8.0-31-generic 
 `oyyyydMMMMysyysoooooodMMMMyyyyyyyyyo`    Uptime: 7 hours, 33 mins 
 oyyyyyydMMMMyyyyyyyyyyyysdMMysssssyyyo    Packages: 3146 (dpkg), 8 (flatpak), 19 (snap) 
-yyyyyyyydMysyyyyyyyyyyyyyysdMMMMMysyyy-   Shell: bash 5.2.21 
oyyyysoodMyyyyyyyyyyyyyyyyyyydMMMMysyyyo   Resolution: 2560x1440, 2560x1440 
yyysdMMMMMyyyyyyyyyyyyyyyyyyysosyyyyyyyy   DE: Plasma 5.27.11 
yyysdMMMMMyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy   WM: KWin 
oyyyyysosdyyyyyyyyyyyyyyyyyyydMMMMysyyyo   Theme: [Plasma], Breeze [GTK2/3] 
-yyyyyyyydMysyyyyyyyyyyyyyysdMMMMMysyyy-   Icons: [Plasma], breeze-dark [GTK2/3] 
 oyyyyyydMMMysyyyyyyyyyyysdMMyoyyyoyyyo    Terminal: konsole 
 `oyyyydMMMysyyyoooooodMMMMyoyyyyyyyyo     CPU: AMD Ryzen 5 3600 (12) @ 3.600GHz 
   oyyysyyoyyyysdMMMMMMMMMMMyyyyyyyyo      GPU: NVIDIA GeForce RTX 3050 6GB 
    -syyyyyyyyydMMMysyyydMMMysyyyys-       Memory: 4244MiB / 32012MiB 
      -oyyyyyyydMMyyyyyyysosyyyyo-
        ./oyyyyyyyyyyyyyyyyyyo/.                                   
           `.:/oosyyyysso/:.`                                      


```
 - Version [e.g. 1.9.0]

**Client App (please complete the following information):**
N/A - does not apply since I was unable to launch the server app

**Required files**
I could not find the files

**Additional context**
going to /snap/deckboard/13 and running `./deckboard` ran the app

It may be that the path info is incorrect.

**Comment by rivafarabi** [comment]
Hi, sorry for the late reply. 
I've just done couple of silent releases for snap distribution lately, with the latest version (3.0.5). I suggest you to try it out.

Let me know if you still have this issue with the latest release.
