### ISSUE TITLE
Deckboard freezing on multiple actions button

### ISSUE THREAD

**Issue by guilhermelimait** [rivafarabi/deckboard#177]
Hi all,
When I'm adding four actions, the program freezes, starts to work again, don't save the button and the changes are not shown.

The actions are:
- Change scene
- Toggle stream
- Toggle recording
- Toggle audio

Sometimes, the button saves, but once it works with OBS, it crashs the app. Any ideas?
I have created one button for each action, and it works fine.

**Comment by rivafarabi** [comment]
is there any delay between the actions?

**Comment by guilhermelimait** [comment]
Nope, just that actions were added to the multiactions. Should I add the delay?

**Comment by rivafarabi** [comment]
I have tried to replicate the issue, and it seems there's no problem with the actions. Can you attach the log.log file located in C:\Users\{USER}\AppData\Roaming\Deckboard for me to analyze it?

**Comment by guilhermelimait** [comment]
Sure, here it is.
Sorry, my network does not allow to upload files, so here is the log itself...

[2019-05-28 08:53:25.713] [error] Something went wrong: Error: spawn adb ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2019-05-28 08:55:06.047] [error] isDev: C:\Users\gu274714\AppData\Local\Programs\Deckboard\resources\app.asar.unpacked\node_modules\node-process-windows + null
[2019-05-28 08:56:39.841] [error] isDev: C:\Users\gu274714\AppData\Local\Programs\Deckboard\resources\app.asar.unpacked\node_modules\node-process-windows + null
[2019-05-28 08:56:51.748] [error] isDev: C:\Users\gu274714\AppData\Local\Programs\Deckboard\resources\app.asar.unpacked\node_modules\node-process-windows + null
[2019-05-28 08:58:26.631] [error] isDev: C:\Users\gu274714\AppData\Local\Programs\Deckboard\resources\app.asar.unpacked\node_modules\node-process-windows + null
[2019-05-28 08:58:34.113] [error] isDev: C:\Users\gu274714\AppData\Local\Programs\Deckboard\resources\app.asar.unpacked\node_modules\node-process-windows + null
[2019-05-28 09:02:46.232] [error] isDev: C:\Users\gu274714\AppData\Local\Programs\Deckboard\resources\app.asar.unpacked\node_modules\node-process-windows + null
[2019-05-28 09:02:52.192] [error] isDev: C:\Users\gu274714\AppData\Local\Programs\Deckboard\resources\app.asar.unpacked\node_modules\node-process-windows + null
[2019-05-28 09:02:55.920] [error] isDev: C:\Users\gu274714\AppData\Local\Programs\Deckboard\resources\app.asar.unpacked\node_modules\node-process-windows + null
[2019-05-28 09:03:05.227] [error] isDev: C:\Users\gu274714\AppData\Local\Programs\Deckboard\resources\app.asar.unpacked\node_modules\node-process-windows + null
[2019-05-28 09:03:12.267] [error] isDev: C:\Users\gu274714\AppData\Local\Programs\Deckboard\resources\app.asar.unpacked\node_modules\node-process-windows + null
[2019-05-28 09:20:27.909] [error] Something went wrong: Error: spawn adb ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by rivafarabi** [comment]
It seems the issue is not recorded in the log itself. Was there any error window showed up when the crash happened?

**Comment by guilhermelimait** [comment]
No, just is not saving the actions... I can try to record the screen if you like

**Comment by rivafarabi** [comment]
both video and exported file of the board would help

**Comment by guilhermelimait** [comment]
![image](https://user-images.githubusercontent.com/14005049/58669253-ef100d00-8311-11e9-8ff8-bc9b5bf8995e.png)

![image](https://user-images.githubusercontent.com/14005049/58669264-fafbcf00-8311-11e9-9371-2f6e8753092f.png)

HI dear,
Got the errors when trying to start the stream tonight

**Comment by guilhermelimait** [comment]
Any ideas? someone?
