### ISSUE TITLE
[1.7.0-RC2] Creating a multi-action always creates a keyboard macro

### ISSUE THREAD

**Issue by Azzurite** [rivafarabi/deckboard#275]
# Reproduction Steps

1. Create a new button
1. Select "Multi Actions" as the action
1. Open Editor
1. Select anything other than "Keyboard macro" as your action
1. Press "Add Action"
1. A keyboard macro will instead be added
1. Pressing this button causes a JS exception:

```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
TypeError: Cannot read property 'split' of null
    at t.default.runKeyPress (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:1:91722)
    at t.default.runCommand (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:1:90677)
    at Timeout.setTimeout (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:1:91457)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
```

**Comment by rivafarabi** [comment]
thanks for the info. I'll check this issue.
