### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by Mbc11** [rivafarabi/deckboard#389]
A JavaScript error occurred in the main process

Uncaught Exception:
Error: ProcessUncIeanExitError: QUERY command exited with code 1:

ERROR: The system was unable to find the specified registry key or value.
at regKey.vaIues
(C:\Users\PCname\deckboard\extentions.temp\voicemeter-control.asar\node_modules\vo...:11)
at ChildProcess.
(C:\Users\PCname\deckboard\extentions.temp\voicemeter-control.asar\node_modules\win...:7)
at ChildProcess.emit (events.js:182:13)
at maybeCIose (internal/child_proess.js:962:16)
at Socket.stream.socket.on (internal/child_process.js:381:11)
at Socket.emlt (events.js:182: 13)
at Pipe._handle.close (net.js:60612)

Deckboard version 1.9.31
OS: Windows 10 Pro
Version: 1909
OS build: 18363.752

Platform specs:
windows 10 Pro 64 bit
intel xeon
gtx1080
12gb Ram

Error appears when opening deckboard then the software functions normal but multimedia functions do not appear and cannot be selected or used.

Any fix would be much appreciated and great work btw.

Many thanks.

**Comment by terenc3** [comment]
This error is cause by the voicemeter-control extension. I've removed voicemeter-control.asar manually from %HOMEPATH%\deckboard\extensions\.temp\ and %HOMEPATH%\deckboard\extensions\

**Comment by Dreamintox** [comment]
Same problem here, but i can't find "voicemeter-control.asar" as you said :(

**Comment by terenc3** [comment]
@Dreamintox What is the content of your error message? As you can see in @Mbc11 error message there is a path given

ERROR: The system was unable to find the specified registry key or value.
at regKey.vaIues
(**C:\Users\PCname\deckboard\extentions.temp\voicemeter-control.asar** [...]

**Comment by Dreamintox** [comment]
![erreur2](https://user-images.githubusercontent.com/22577171/81662506-facee380-943d-11ea-8679-751815147d3f.png)
 :/

Even if i delete both files you told me, there's still an error popping :/
