### ISSUE TITLE
Node issue when trying to run AppImage on Linux

### ISSUE THREAD

**Issue by jonasmac16** [rivafarabi/deckboard#558]
Hi,

I was trying to run the AppImage on Manjaro but when I launched it from the terminal I got the following error:

```bash
Checking for update
node-pre-gyp info This Node instance does not support builds for N-API version 6
node-pre-gyp info This Node instance does not support builds for N-API version 6
Knex: run
$ npm install sqlite3 --save
Error: libnode.so.64: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/tmp/.mount_DeckboWWSC05/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Object.<anonymous> (/tmp/.mount_DeckboWWSC05/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/tmp/.mount_DeckboWWSC05/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:2:15)
    at Object.<anonymous> (/tmp/.mount_DeckboWWSC05/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:207:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Client_SQLite3._driver (/tmp/.mount_DeckboWWSC05/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:79:12)
    at Client_SQLite3.initializeDriver (/tmp/.mount_DeckboWWSC05/resources/app.asar/node_modules/knex/lib/client.js:254:26)
[14:13:23.304] [error] adb:startDeviceTracker Error: spawn adb ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:52647) UnhandledPromiseRejectionWarning: Error: spawn adb ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:52647) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:52647) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Unhandled rejection TypeError: Cannot read property 'Database' of undefined
    at /tmp/.mount_DeckboWWSC05/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:106:33
    at Promise._execute (/tmp/.mount_DeckboWWSC05/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/tmp/.mount_DeckboWWSC05/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/tmp/.mount_DeckboWWSC05/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_SQLite3.acquireRawConnection (/tmp/.mount_DeckboWWSC05/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:105:12)
    at create (/tmp/.mount_DeckboWWSC05/resources/app.asar/node_modules/knex/lib/client.js:283:23)
    at utils_1.tryPromise (/tmp/.mount_DeckboWWSC05/resources/app.asar/node_modules/tarn/lib/Pool.js:315:34)
    at Object.tryPromise (/tmp/.mount_DeckboWWSC05/resources/app.asar/node_modules/tarn/lib/utils.js:53:24)
    at Promise (/tmp/.mount_DeckboWWSC05/resources/app.asar/node_modules/tarn/lib/Pool.js:315:17)
    at new Promise (<anonymous>)
    at callbackOrPromise (/tmp/.mount_DeckboWWSC05/resources/app.asar/node_modules/tarn/lib/Pool.js:306:12)
    at Pool._create (/tmp/.mount_DeckboWWSC05/resources/app.asar/node_modules/tarn/lib/Pool.js:236:9)
    at Pool._doCreate (/tmp/.mount_DeckboWWSC05/resources/app.asar/node_modules/tarn/lib/Pool.js:208:36)
    at Pool._tryAcquireOrCreate (/tmp/.mount_DeckboWWSC05/resources/app.asar/node_modules/tarn/lib/Pool.js:159:18)
    at Pool.acquire (/tmp/.mount_DeckboWWSC05/resources/app.asar/node_modules/tarn/lib/Pool.js:85:14)
    at /tmp/.mount_DeckboWWSC05/resources/app.asar/node_modules/knex/lib/client.js:336:26
    at tryCatcher (/tmp/.mount_DeckboWWSC05/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/tmp/.mount_DeckboWWSC05/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/method.js:39:29)
    at Client_SQLite3.acquireConnection (/tmp/.mount_DeckboWWSC05/resources/app.asar/node_modules/knex/lib/client.js:335:34)
    at Runner.ensureConnection (/tmp/.mount_DeckboWWSC05/resources/app.asar/node_modules/knex/lib/runner.js:233:24)
    at Runner.run (/tmp/.mount_DeckboWWSC05/resources/app.asar/node_modules/knex/lib/runner.js:47:42)
    at Builder.Target.then (/tmp/.mount_DeckboWWSC05/resources/app.asar/node_modules/knex/lib/interface.js:39:43)
    at t.default.connectDatabase (/tmp/.mount_DeckboWWSC05/resources/app.asar/dist/main/index.js:1:143590)
    at u.default.exists.e (/tmp/.mount_DeckboWWSC05/resources/app.asar/dist/main/index.js:1:149754)
    at suppressedCallback (fs.js:200:5)
    at FSReqWrap.oncomplete (fs.js:141:20)
```

Any idea how to solve this? Node version is `v15.0.1`

**Comment by BOUSILLOR** [comment]
Very same here on Gentoo if sb have an idea?
Tried to merge nodejs and do LD_PRELOAD= and LD_PRELOAD= without success.
Tried to extract libnode.so.64 from an rpm to point to too

**Comment by jonasmac16** [comment]
@BOUSILLOR Have you had any success yet? @rivafarabi Do you have any idea how to resolve this?

**Comment by BOUSILLOR** [comment]
@jonasmac16  Ha! No, it's in my ToDo List as I had priority tasks to do : I'll try to run it in a VM (ubuntu?).
I think the AppImage is lacking a lot of libraries and need to be rebuild, on that note, the Tachiweb-server (https://github.com/TachiWeb/TachiWeb-Server) run on my machine and so is the Atom one. 
I think Atom is build on Electron and electron is on Node.js? So I'll look into it deeper as soon as I have time as I'll like to benefit from the deckboard accessibility

**Comment by davidlaym-glb** [comment]
Same issue on ubuntu 18.04 both with AppImage and .deb installs. This looked very promising as it advertises Linux support, but I see it's not there yet.

**Comment by MessiasLima** [comment]
Same problem here.
Pop-OS 20.10
I tested on 20.04 and it worked well

**Comment by BOUSILLOR** [comment]
@jonasmac16  well sorry for the delay, but now the lastest appimage is working (v.1.9.96), in case you've missed that. I'll try the tarball once I have time to do an ebuild for it.
You'll need to make your firewall accept tcp 8500:8501 for the app to hook up. Server ports should be documented somewhere or at least told in the in-app/server connection window.
Also I just tested basic functions but it seems ok.
