### ISSUE TITLE
Cannot open deckboard, no loading, no crash, when I click it it just doesn't do anything.

### ISSUE THREAD

**Issue by modcolocko** [rivafarabi/deckboard#628]
I am running pop os, basically unbuntu, and have installed the deb deckboard file using eddy, the icon shows up in the apps menu but when clicking on the icon nothing happens.

**Comment by barcelosluan** [comment]
Running at Debian 10 it is the same (.deb installed), but trying to open it at the terminal by simply ```deckboard``` it returns the error log below:
```
$ deckboard
{ appDir: '/home/barcelosluan/deckboard',
  os: '/home/barcelosluan' }
Checking for update
node-pre-gyp info This Node instance does not support builds for N-API version 6
node-pre-gyp info This Node instance does not support builds for N-API version 6
Knex: run
$ npm install sqlite3 --save
Error: libnode.so.64: nÃ£o Ã© possÃ­vel abrir arquivo compartilhado: Arquivo ou diretÃ³rio inexistente
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/opt/Deckboard/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Object.<anonymous> (/opt/Deckboard/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/opt/Deckboard/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:2:15)
    at Object.<anonymous> (/opt/Deckboard/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:207:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Client_SQLite3._driver (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:79:12)
    at Client_SQLite3.initializeDriver (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/client.js:254:26)
[00:54:48.546] [error] ext:cleanTemp Error: ENOENT: no such file or directory, scandir '/home/barcelosluan/deckboard/temp'
    at Object.readdirSync (fs.js:764:3)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:641:39)
    at /opt/Deckboard/resources/app.asar/dist/main/index.js:1:65722
    at Generator.next (<anonymous>)
    at n (/opt/Deckboard/resources/app.asar/dist/main/index.js:1:12032)
    at /opt/Deckboard/resources/app.asar/dist/main/index.js:1:12128
    at process._tickCallback (internal/process/next_tick.js:68:7)

Error: Error: ENOENT: no such file or directory, open '/opt/Deckboard/resources/app-update.yml'
(node:29090) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/opt/Deckboard/resources/app-update.yml'
(node:29090) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:29090) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[00:54:48.564] [error] adb:startDeviceTracker Error: spawn adb ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:29090) UnhandledPromiseRejectionWarning: Error: spawn adb ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:29090) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
Unhandled rejection TypeError: Cannot read property 'Database' of undefined
    at /opt/Deckboard/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:106:33
    at Promise._execute (/opt/Deckboard/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/opt/Deckboard/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/opt/Deckboard/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_SQLite3.acquireRawConnection (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:105:12)
    at create (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/client.js:283:23)
    at utils_1.tryPromise (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/Pool.js:315:34)
    at Object.tryPromise (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/utils.js:53:24)
    at Promise (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/Pool.js:315:17)
    at new Promise (<anonymous>)
    at callbackOrPromise (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/Pool.js:306:12)
    at Pool._create (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/Pool.js:236:9)
    at Pool._doCreate (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/Pool.js:208:36)
    at Pool._tryAcquireOrCreate (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/Pool.js:159:18)
    at Pool.acquire (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/Pool.js:85:14)
    at /opt/Deckboard/resources/app.asar/node_modules/knex/lib/client.js:336:26
    at tryCatcher (/opt/Deckboard/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/opt/Deckboard/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/method.js:39:29)
    at Client_SQLite3.acquireConnection (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/client.js:335:34)
    at Runner.ensureConnection (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/runner.js:233:24)
    at Runner.run (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/runner.js:47:42)
    at Builder.Target.then (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/interface.js:39:43)
    at e.default.connectDatabase (/opt/Deckboard/resources/app.asar/dist/main/index.js:1:1495049)
    at c.default.exists.B (/opt/Deckboard/resources/app.asar/dist/main/index.js:1:1501213)
    at suppressedCallback (fs.js:200:5)
    at FSReqWrap.oncomplete (fs.js:141:20)

```

**Comment by pedrovillalobos** [comment]
> Running at Debian 10 it is the same (deckboard_1.9.84_amd64.deb installed), but trying to open it at the terminal by simply `deckboard` it returns the error log below:
> 
> ```
> $ deckboard
> { appDir: '/home/barcelosluan/deckboard',
>   os: '/home/barcelosluan' }
> Checking for update
> node-pre-gyp info This Node instance does not support builds for N-API version 6
> node-pre-gyp info This Node instance does not support builds for N-API version 6
> Knex: run
> $ npm install sqlite3 --save
> Error: libnode.so.64: nÃ£o Ã© possÃ­vel abrir arquivo compartilhado: Arquivo ou diretÃ³rio inexistente
>     at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
>     at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
>     at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
>     at Module.load (internal/modules/cjs/loader.js:602:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:533:3)
>     at Module.require (internal/modules/cjs/loader.js:640:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at Object.<anonymous> (/opt/Deckboard/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
>     at Object.<anonymous> (/opt/Deckboard/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:7:3)
>     at Module._compile (internal/modules/cjs/loader.js:693:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
>     at Module.load (internal/modules/cjs/loader.js:602:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:533:3)
>     at Module.require (internal/modules/cjs/loader.js:640:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at Object.<anonymous> (/opt/Deckboard/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:2:15)
>     at Object.<anonymous> (/opt/Deckboard/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:207:3)
>     at Module._compile (internal/modules/cjs/loader.js:693:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
>     at Module.load (internal/modules/cjs/loader.js:602:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:533:3)
>     at Module.require (internal/modules/cjs/loader.js:640:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at Client_SQLite3._driver (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:79:12)
>     at Client_SQLite3.initializeDriver (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/client.js:254:26)
> [00:54:48.546] [error] ext:cleanTemp Error: ENOENT: no such file or directory, scandir '/home/barcelosluan/deckboard/temp'
>     at Object.readdirSync (fs.js:764:3)
>     at Object.fs.readdirSync (ELECTRON_ASAR.js:641:39)
>     at /opt/Deckboard/resources/app.asar/dist/main/index.js:1:65722
>     at Generator.next (<anonymous>)
>     at n (/opt/Deckboard/resources/app.asar/dist/main/index.js:1:12032)
>     at /opt/Deckboard/resources/app.asar/dist/main/index.js:1:12128
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> 
> Error: Error: ENOENT: no such file or directory, open '/opt/Deckboard/resources/app-update.yml'
> (node:29090) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/opt/Deckboard/resources/app-update.yml'
> (node:29090) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:29090) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> [00:54:48.564] [error] adb:startDeviceTracker Error: spawn adb ENOENT
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
>     at onErrorNT (internal/child_process.js:407:16)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
> (node:29090) UnhandledPromiseRejectionWarning: Error: spawn adb ENOENT
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
>     at onErrorNT (internal/child_process.js:407:16)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
> (node:29090) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
> Unhandled rejection TypeError: Cannot read property 'Database' of undefined
>     at /opt/Deckboard/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:106:33
>     at Promise._execute (/opt/Deckboard/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/debuggability.js:313:9)
>     at Promise._resolveFromExecutor (/opt/Deckboard/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/promise.js:483:18)
>     at new Promise (/opt/Deckboard/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/promise.js:79:10)
>     at Client_SQLite3.acquireRawConnection (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:105:12)
>     at create (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/client.js:283:23)
>     at utils_1.tryPromise (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/Pool.js:315:34)
>     at Object.tryPromise (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/utils.js:53:24)
>     at Promise (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/Pool.js:315:17)
>     at new Promise (<anonymous>)
>     at callbackOrPromise (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/Pool.js:306:12)
>     at Pool._create (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/Pool.js:236:9)
>     at Pool._doCreate (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/Pool.js:208:36)
>     at Pool._tryAcquireOrCreate (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/Pool.js:159:18)
>     at Pool.acquire (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/Pool.js:85:14)
>     at /opt/Deckboard/resources/app.asar/node_modules/knex/lib/client.js:336:26
>     at tryCatcher (/opt/Deckboard/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
>     at Function.Promise.attempt.Promise.try (/opt/Deckboard/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/method.js:39:29)
>     at Client_SQLite3.acquireConnection (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/client.js:335:34)
>     at Runner.ensureConnection (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/runner.js:233:24)
>     at Runner.run (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/runner.js:47:42)
>     at Builder.Target.then (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/interface.js:39:43)
>     at e.default.connectDatabase (/opt/Deckboard/resources/app.asar/dist/main/index.js:1:1495049)
>     at c.default.exists.B (/opt/Deckboard/resources/app.asar/dist/main/index.js:1:1501213)
>     at suppressedCallback (fs.js:200:5)
>     at FSReqWrap.oncomplete (fs.js:141:20)
> ```

Same error here. Ubuntu 20.10 - 5.8.0-38-generic

**Comment by stud4nte** [comment]
I'm with the same problem when I open appimage and deb version in PopOS 20.10, also the snap version doesn't open.

**Comment by Thelvaen** [comment]
Yeah same issue, already reported in issue #617, the appimage package is missing some libs.

**Comment by pedrovillalobos** [comment]
> Yeah same issue, already reported in issue #617, the appimage package is missing some libs.
> 
> @stud4nte try downloading and installing those package:
> libicu66_66.1-2ubuntu2_amd64.deb
> libnode64_10.19.0_dfsg-3ubuntu1_amd64.deb
> 
> Those are dependancies that are not included in the AppImage (when they should) and they are not registered as dependancies either for the .deb package.

Installing libnode64 (libcu66 was already installed) solved my issue and it now opens :)

For reference, this is the one I manually installed http://archive.ubuntu.com/ubuntu/pool/universe/n/nodejs/libnode64_10.19.0~dfsg-3ubuntu1_amd64.deb

**Comment by stud4nte** [comment]
> Yeah same issue, already reported in issue #617, the appimage package is missing some libs.
> 
> @stud4nte try downloading and installing those package:
> libicu66_66.1-2ubuntu2_amd64.deb
> libnode64_10.19.0_dfsg-3ubuntu1_amd64.deb
> 
> Those are dependancies that are not included in the AppImage (when they should) and they are not registered as dependancies either for the .deb package.

After install this packages the deb version worked. Thanks!

**Comment by ModcoLocko** [comment]
> Yeah same issue, already reported in issue #617, the appimage package is missing some libs.
> 
> @stud4nte try downloading and installing those package:
> libicu66_66.1-2ubuntu2_amd64.deb
> libnode64_10.19.0_dfsg-3ubuntu1_amd64.deb
> 
> Those are dependancies that are not included in the AppImage (when they should) and they are not registered as dependancies either for the .deb package.

Linux noob here, how exactly would you do that.

**Comment by stud4nte** [comment]
> > Yeah same issue, already reported in issue #617, the appimage package is missing some libs.
> > @stud4nte try downloading and installing those package:
> > libicu66_66.1-2ubuntu2_amd64.deb
> > libnode64_10.19.0_dfsg-3ubuntu1_amd64.deb
> > Those are dependancies that are not included in the AppImage (when they should) and they are not registered as dependancies either for the .deb package.
> 
> Linux noob here, how exactly would you do that.

I installed this files manually: 
http://archive.ubuntu.com/ubuntu/pool/main/i/icu/libicu66_66.1-2ubuntu2_amd64.deb
http://archive.ubuntu.com/ubuntu/pool/universe/n/nodejs/libnode64_10.19.0~dfsg-3ubuntu1_amd64.deb

**Comment by Thelvaen** [comment]
> > Yeah same issue, already reported in issue #617, the appimage package is missing some libs.
> > @stud4nte try downloading and installing those package:
> > libicu66_66.1-2ubuntu2_amd64.deb
> > libnode64_10.19.0_dfsg-3ubuntu1_amd64.deb
> > Those are dependancies that are not included in the AppImage (when they should) and they are not registered as dependancies either for the .deb package.
> 
> Linux noob here, how exactly would you do that.

download files from @stud4nte comment, then just run a shell, and in it run
sudo dpkg -i libicu66_66.1-2ubuntu2_amd64.deb
sudo dpkg -i libnode64_10.19.0~dfsg-3ubuntu1_amd64.deb
in the folder where you downloaded the files.

**Comment by ModcoLocko** [comment]
> > > Yeah same issue, already reported in issue #617, the appimage package is missing some libs.
> > > @stud4nte try downloading and installing those package:
> > > libicu66_66.1-2ubuntu2_amd64.deb
> > > libnode64_10.19.0_dfsg-3ubuntu1_amd64.deb
> > > Those are dependancies that are not included in the AppImage (when they should) and they are not registered as dependancies either for the .deb package.
> > 
> > 
> > Linux noob here, how exactly would you do that.
> 
> download files from @stud4nte comment, then just run a shell, and in it run
> sudo dpkg -i libicu66_66.1-2ubuntu2_amd64.deb
> sudo dpkg -i libnode64_10.19.0~dfsg-3ubuntu1_amd64.deb
> in the folder where you downloaded the files.

Can you please explain what the -i does, I know it changes how the dpkg works but what does it do specificly

**Comment by Thelvaen** [comment]
as per "man dpkg", the "-i" is for "install"
