### ISSUE TITLE
Failed to run Deckboard after install on Linux Mint 20.1

### ISSUE THREAD

**Issue by Alexsussa** [rivafarabi/deckboard#634]
./Deckboard-1.9.84.AppImage 
{ appDir: '/home/user/deckboard', os: '/home/user' }
Checking for update
node-pre-gyp info This Node instance does not support builds for N-API version 6
node-pre-gyp info This Node instance does not support builds for N-API version 6
Knex: run
$ npm install sqlite3 --save
Error: libnode.so.64: nÃ£o Ã© possÃ­vel abrir arquivo compartilhado: Arquivo ou diretÃ³rio nÃ£o encontrado
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/tmp/.mount_DeckboGlAhQc/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Object.<anonymous> (/tmp/.mount_DeckboGlAhQc/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/tmp/.mount_DeckboGlAhQc/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:2:15)
    at Object.<anonymous> (/tmp/.mount_DeckboGlAhQc/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:207:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Client_SQLite3._driver (/tmp/.mount_DeckboGlAhQc/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:79:12)
    at Client_SQLite3.initializeDriver (/tmp/.mount_DeckboGlAhQc/resources/app.asar/node_modules/knex/lib/client.js:254:26)
[18:53:44.890] [error] ext:cleanTemp Error: ENOENT: no such file or directory, scandir '/home/user/deckboard/temp'
    at Object.readdirSync (fs.js:764:3)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:641:39)
    at /tmp/.mount_DeckboGlAhQc/resources/app.asar/dist/main/index.js:1:65722
    at Generator.next (<anonymous>)
    at n (/tmp/.mount_DeckboGlAhQc/resources/app.asar/dist/main/index.js:1:12032)
    at /tmp/.mount_DeckboGlAhQc/resources/app.asar/dist/main/index.js:1:12128
    at process._tickCallback (internal/process/next_tick.js:68:7)

Unhandled rejection TypeError: Cannot read property 'Database' of undefined
    at /tmp/.mount_DeckboGlAhQc/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:106:33
    at Promise._execute (/tmp/.mount_DeckboGlAhQc/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/tmp/.mount_DeckboGlAhQc/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/tmp/.mount_DeckboGlAhQc/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_SQLite3.acquireRawConnection (/tmp/.mount_DeckboGlAhQc/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:105:12)
    at create (/tmp/.mount_DeckboGlAhQc/resources/app.asar/node_modules/knex/lib/client.js:283:23)
    at utils_1.tryPromise (/tmp/.mount_DeckboGlAhQc/resources/app.asar/node_modules/tarn/lib/Pool.js:315:34)
    at Object.tryPromise (/tmp/.mount_DeckboGlAhQc/resources/app.asar/node_modules/tarn/lib/utils.js:53:24)
    at Promise (/tmp/.mount_DeckboGlAhQc/resources/app.asar/node_modules/tarn/lib/Pool.js:315:17)
    at new Promise (<anonymous>)
    at callbackOrPromise (/tmp/.mount_DeckboGlAhQc/resources/app.asar/node_modules/tarn/lib/Pool.js:306:12)
    at Pool._create (/tmp/.mount_DeckboGlAhQc/resources/app.asar/node_modules/tarn/lib/Pool.js:236:9)
    at Pool._doCreate (/tmp/.mount_DeckboGlAhQc/resources/app.asar/node_modules/tarn/lib/Pool.js:208:36)
    at Pool._tryAcquireOrCreate (/tmp/.mount_DeckboGlAhQc/resources/app.asar/node_modules/tarn/lib/Pool.js:159:18)
    at Pool.acquire (/tmp/.mount_DeckboGlAhQc/resources/app.asar/node_modules/tarn/lib/Pool.js:85:14)
    at /tmp/.mount_DeckboGlAhQc/resources/app.asar/node_modules/knex/lib/client.js:336:26
    at tryCatcher (/tmp/.mount_DeckboGlAhQc/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/tmp/.mount_DeckboGlAhQc/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/method.js:39:29)
    at Client_SQLite3.acquireConnection (/tmp/.mount_DeckboGlAhQc/resources/app.asar/node_modules/knex/lib/client.js:335:34)
    at Runner.ensureConnection (/tmp/.mount_DeckboGlAhQc/resources/app.asar/node_modules/knex/lib/runner.js:233:24)
    at Runner.run (/tmp/.mount_DeckboGlAhQc/resources/app.asar/node_modules/knex/lib/runner.js:47:42)
    at Builder.Target.then (/tmp/.mount_DeckboGlAhQc/resources/app.asar/node_modules/knex/lib/interface.js:39:43)
    at e.default.connectDatabase (/tmp/.mount_DeckboGlAhQc/resources/app.asar/dist/main/index.js:1:1495049)
    at c.default.exists.B (/tmp/.mount_DeckboGlAhQc/resources/app.asar/dist/main/index.js:1:1501213)
    at suppressedCallback (fs.js:200:5)
    at FSReqWrap.oncomplete (fs.js:141:20)

**Comment by Alexsussa** [comment]
Dear, developer, i just found the solution some minutes after open that issue.
To resolve the problem i reported just use that command bellow:
sudo apt install libnode64
After that Deckboard run normamally.
