### ISSUE TITLE
[BUG] Can't open on Fedora

### ISSUE THREAD

**Issue by raulcraveiro** [rivafarabi/deckboard#641]
**Describe the bug**
I try to open Deckboard on Fedora, but I get an error.

**To Reproduce**
1. Install Deckboard on Fedora
2. Try to open it

**Server App (please complete the following information):**
 - OS: Fedora 33 Workstation

**Additional context**

I've tried to open via terminal and got the following error:

`Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
{ appDir: '/home/raul/deckboard', os: '/home/raul' }
Checking for update
node-pre-gyp info This Node instance does not support builds for N-API version 6
node-pre-gyp info This Node instance does not support builds for N-API version 6
Knex: run
$ npm install sqlite3 --save
Error: libnode.so.64: nÃ£o Ã© possÃ­vel abrir arquivo compartilhado: Arquivo ou diretÃ³rio inexistente
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/opt/Deckboard/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Object.<anonymous> (/opt/Deckboard/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/opt/Deckboard/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:2:15)
    at Object.<anonymous> (/opt/Deckboard/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:207:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Client_SQLite3._driver (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:79:12)
    at Client_SQLite3.initializeDriver (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/client.js:254:26)
[23:23:00.757] [error] ext:cleanTemp Error: ENOENT: no such file or directory, scandir '/home/raul/deckboard/temp'
    at Object.readdirSync (fs.js:764:3)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:641:39)
    at /opt/Deckboard/resources/app.asar/dist/main/index.js:1:65722
    at Generator.next (<anonymous>)
    at n (/opt/Deckboard/resources/app.asar/dist/main/index.js:1:12032)
    at /opt/Deckboard/resources/app.asar/dist/main/index.js:1:12128
    at process._tickCallback (internal/process/next_tick.js:68:7)

Error: Error: ENOENT: no such file or directory, open '/opt/Deckboard/resources/app-update.yml'
(node:82265) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/opt/Deckboard/resources/app-update.yml'
(node:82265) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:82265) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Unhandled rejection TypeError: Cannot read property 'Database' of undefined
    at /opt/Deckboard/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:106:33
    at Promise._execute (/opt/Deckboard/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/opt/Deckboard/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/opt/Deckboard/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_SQLite3.acquireRawConnection (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:105:12)
    at create (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/client.js:283:23)
    at utils_1.tryPromise (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/Pool.js:315:34)
    at Object.tryPromise (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/utils.js:53:24)
    at Promise (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/Pool.js:315:17)
    at new Promise (<anonymous>)
    at callbackOrPromise (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/Pool.js:306:12)
    at Pool._create (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/Pool.js:236:9)
    at Pool._doCreate (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/Pool.js:208:36)
    at Pool._tryAcquireOrCreate (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/Pool.js:159:18)
    at Pool.acquire (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/Pool.js:85:14)
    at /opt/Deckboard/resources/app.asar/node_modules/knex/lib/client.js:336:26
    at tryCatcher (/opt/Deckboard/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/opt/Deckboard/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/method.js:39:29)
    at Client_SQLite3.acquireConnection (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/client.js:335:34)
    at Runner.ensureConnection (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/runner.js:233:24)
    at Runner.run (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/runner.js:47:42)
    at Builder.Target.then (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/interface.js:39:43)
    at e.default.connectDatabase (/opt/Deckboard/resources/app.asar/dist/main/index.js:1:1495049)
    at c.default.exists.B (/opt/Deckboard/resources/app.asar/dist/main/index.js:1:1501213)
    at suppressedCallback (fs.js:200:5)
    at FSReqWrap.oncomplete (fs.js:141:20)`

**Comment by javicv** [comment]
Same problem here, Fedora 33 and Deckboard 1.9.84. I tried versions from 1.9.70-beta4 with the same result

Looking into open issues I think this is related with issue https://github.com/rivafarabi/deckboard/issues/628, which is still open but people reported to find a solution with a missing dependency. I installed nodejs and libicu with dnf but the problem is still there.

**Comment by mauriandres** [comment]
Same here on Fedora 33. I cannot find the fedora equivalent for the debian package `libnode64`.

**Comment by javicv** [comment]
I tried the latest release 1.9.85, but this bug is still there. Same output error, I stil haven't found a workaround for this.

**Comment by javicv** [comment]
> Same here on Fedora 33. I cannot find the fedora equivalent for the debian package `libnode64`.

Hi @mauriandres 

In Fedora 33 the library _libnode.so_ is provided by the package _nodejs-libs_, which provides _libnode.so.83_. Just to reference it here, libicu is provided by the package _libicu_

I have both of them installed, but the problem is still there, so there must be another dependency or issue which is different in Fedora and Debian-based distributions. For me, AppImage isn't working too.

```
❯ rpm -qf /usr/lib64/libnode*
nodejs-libs-14.15.4-1.fc33.x86_64
❯ rpm -qf /usr/lib64/libicu*
libicu-67.1-4.fc33.x86_64
```
Hopefully, @rivafarabi could shed some light on this, as it seems to be a dependency issue.

**Comment by javicv** [comment]
> Same here on Fedora 33. I cannot find the fedora equivalent for the debian package `libnode64`.

Hi @mauriandres 

In Fedora 33 the library _libnode.so_ is provided by the package _nodejs-libs_, which provides by default _libnode.so.83_.
```
❯ rpm -ql nodejs-libs
...
/usr/lib64/libnode.so.83
/usr/lib64/libv8.so.8
/usr/lib64/libv8_libbase.so.8
/usr/lib64/libv8_libplatform.so.8
...
```
As you can see, I have both of them installed, but the problem is still there, so I tried installing _libnode.so.64_, to do this you need to change to module stream nodejs:10
```
❯ sudo dnf module reset nodejs
...
❯ sudo dnf module install nodejs:10
...
❯ rpm -ql nodejs-libs
...
/usr/lib64/libnode.so.64
/usr/lib64/libv8.so.6
/usr/lib64/libv8_libbase.so.6
/usr/lib64/libv8_libplatform.so.6
...
❯ node -v
v10.23.1
❯ npm -v
6.14.10
```
But after doing this, _deckboard_ doesn't work either. I tried both RPM and AppImage, with the same result.
```
❯ deckboard
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
{ appDir: '/home/javicv/deckboard', os: '/home/javicv' }
Checking for update
node-pre-gyp info This Node instance does not support builds for N-API version 6
node-pre-gyp info This Node instance does not support builds for N-API version 6
[1]    13233 segmentation fault (core dumped)  deckboard
❯ ./Deckboard-1.9.85.AppImage
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
{ appDir: '/home/javicv/deckboard', os: '/home/javicv' }
Checking for update
node-pre-gyp info This Node instance does not support builds for N-API version 6
node-pre-gyp info This Node instance does not support builds for N-API version 6
[1]    13540 segmentation fault (core dumped)  ./Deckboard-1.9.85.AppImage
```
Hopefully, @rivafarabi could shed some light on this, as it seems to be a dependency or nodejs issue, and I'm not very familiar with nodejs.

**Comment by mauriandres** [comment]
Thanks @javicv . I also tried to track down and install the `libnode.so` dependency by looking at the build information for [`nodejs-devel`](https://koji.fedoraproject.org/koji/rpminfo?rpmID=24454215). Thanks for showing me `rpm -ql`.

@by-lucas on #609 installed it via `snap install --beta deckboard` and this worked for me on Fedora 33. I suppose the snap package manages to include all dependencies.

For traceability, it looks like #558 is also related.

**Comment by javicv** [comment]
I installed the latest version (1.9.86) and the error is different, now it can't find "jimp" module.
Both the RPM package:
![image](https://user-images.githubusercontent.com/18577298/110218013-ac507100-7eb7-11eb-90cd-f3a5d86282d7.png)
And the AppImage:
![image](https://user-images.githubusercontent.com/18577298/110218188-90999a80-7eb8-11eb-885b-e1d9052d27f0.png)

**Comment by rivafarabi** [comment]
> I installed the latest version (1.9.86) and the error is different, now it can't find "jimp" module.
> Both the RPM package:
> ![image](https://user-images.githubusercontent.com/18577298/110218013-ac507100-7eb7-11eb-90cd-f3a5d86282d7.png)
> And the AppImage:
> ![image](https://user-images.githubusercontent.com/18577298/110218188-90999a80-7eb8-11eb-885b-e1d9052d27f0.png)

This issue has been fixed in version [1.9.88](https://github.com/rivafarabi/deckboard/releases/tag/v1.9.88)

**Comment by raulcraveiro** [comment]
@rivafarabi Just tested the 1.9.88 RPM version and I'm getting another error:

Gtk-Message: 18:21:09.070: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:21:09.070: Failed to load module "pk-gtk-module"
Gtk-Message: 18:21:09.071: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:21:09.071: Failed to load module "pk-gtk-module"
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.org.chromium.Chromium.bPznVU: classe ELF errada: ELFCLASS64
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/opt/Deckboard/resources/app.asar/node_modules/robotjs/index.js:1:170)
    at Object.<anonymous> (/opt/Deckboard/resources/app.asar/node_modules/robotjs/index.js:38:3)
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"

**Comment by Pedroassuncao** [comment]
fedora 34 beta

installed RPM version

terminal output

❯ deckboard                  
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
{ appDir: '/home/scars/deckboard', os: '/home/scars' }
Checking for update
node-pre-gyp info This Node instance does not support builds for N-API version 6
node-pre-gyp info This Node instance does not support builds for N-API version 6
Knex: run
$ npm install sqlite3 --save
Error: libnode.so.64: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/opt/Deckboard/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Object.<anonymous> (/opt/Deckboard/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/opt/Deckboard/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:2:15)
    at Object.<anonymous> (/opt/Deckboard/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:207:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Client_SQLite3._driver (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:79:12)
    at Client_SQLite3.initializeDriver (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/client.js:254:26)
[00:19:40.585] [error] ext:cleanTemp Error: ENOENT: no such file or directory, scandir '/home/scars/deckboard/temp'
    at Object.readdirSync (fs.js:764:3)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:641:39)
    at /opt/Deckboard/resources/app.asar/dist/main/index.js:1:68525
    at Generator.next (<anonymous>)
    at n (/opt/Deckboard/resources/app.asar/dist/main/index.js:1:8915)
    at /opt/Deckboard/resources/app.asar/dist/main/index.js:1:9011
    at process._tickCallback (internal/process/next_tick.js:68:7)

Error: Error: ENOENT: no such file or directory, open '/opt/Deckboard/resources/app-update.yml'
(node:5710) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/opt/Deckboard/resources/app-update.yml'
(node:5710) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5710) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[00:19:40.614] [error] adb:startDeviceTracker Error: spawn adb ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:5710) UnhandledPromiseRejectionWarning: Error: spawn adb ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:5710) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
Unhandled rejection TypeError: Cannot read property 'Database' of undefined
    at /opt/Deckboard/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:106:33
    at Promise._execute (/opt/Deckboard/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/opt/Deckboard/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/opt/Deckboard/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_SQLite3.acquireRawConnection (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:105:12)
    at create (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/client.js:283:23)
    at utils_1.tryPromise (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/Pool.js:315:34)
    at Object.tryPromise (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/utils.js:53:24)
    at Promise (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/Pool.js:315:17)
    at new Promise (<anonymous>)
    at callbackOrPromise (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/Pool.js:306:12)
    at Pool._create (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/Pool.js:236:9)
    at Pool._doCreate (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/Pool.js:208:36)
    at Pool._tryAcquireOrCreate (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/Pool.js:159:18)
    at Pool.acquire (/opt/Deckboard/resources/app.asar/node_modules/tarn/lib/Pool.js:85:14)
    at /opt/Deckboard/resources/app.asar/node_modules/knex/lib/client.js:336:26
    at tryCatcher (/opt/Deckboard/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/opt/Deckboard/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/method.js:39:29)
    at Client_SQLite3.acquireConnection (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/client.js:335:34)
    at Runner.ensureConnection (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/runner.js:233:24)
    at Runner.run (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/runner.js:47:42)
    at Builder.Target.then (/opt/Deckboard/resources/app.asar/node_modules/knex/lib/interface.js:39:43)
    at e.default.connectDatabase (/opt/Deckboard/resources/app.asar/dist/main/index.js:1:1501871)
    at c.default.exists.B (/opt/Deckboard/resources/app.asar/dist/main/index.js:1:1508139)
    at suppressedCallback (fs.js:200:5)
    at FSReqWrap.oncomplete (fs.js:141:20)
