### ISSUE TITLE
[BUG] Insane CPU Usage

### ISSUE THREAD

**Issue by Azrael907** [rivafarabi/deckboard#648]
**Describe the bug**

While streaming this morning my system started wildly lagging up.   My gameplay was severely impacted to the point where we were all running in slow motion.   Apps started completely frezing and crashed due to this insane CPU spike caused by DeckBoard.

My system is an AMD Threadripper with 32gb of 3600 OC+ DDR.   Normal CPU use for streaming and associated apps for streaming with a game like Apex for example is less than 40%.

I immediately opened Task Manager because it felt like my system was under attack.   I saw that DeckBoard was responsible for spiking my CPU at 100%!   Let me repeat...  A Threadripper.   The app normally uses less than 1%.  This is highly unacceptable and i don't know what it was doing,

Upon terminating the process it caused a cascade of errors in taskmanager saying:  Unable to Terminate Process.

**Expected behavior**
I expect it to only use minimal CPU (less than 1%) like it was previously,

**Client App (please complete the following information):**
 - OS: Android 10

**Required files**
- database.db (located in `C:\Users%USER%\deckboard`)
- log.log (located in located in `C:\Users%USER%\AppData\Roaming\Deckboard`)
Log Snippet For This Instance:
[2021-02-14 02:49:06.147] [error] ext:cleanTemp Error: ENOENT: no such file or directory, scandir 'C:\Users\alask\deckboard\temp'
    at Object.readdirSync (fs.js:764:3)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:641:39)
    at C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:1:63230
    at Generator.next (<anonymous>)
    at n (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:1:11970)
    at C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:1:12066
    at process._tickCallback (internal/process/next_tick.js:68:7)

[2021-02-14 02:49:07.617] [error] ext:cleanTemp Error: ENOENT: no such file or directory, scandir 'C:\Users\alask\deckboard\temp'
    at Object.readdirSync (fs.js:764:3)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:641:39)
    at C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:1:63230
    at Generator.next (<anonymous>)
    at n (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:1:11970)
    at C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:1:12066

[2021-02-14 02:49:08.023] [error] adb:startDeviceTracker Error: spawn adb ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Additional context**

Love the app, just don't want it crashing my PC

**Comment by medoro** [comment]
Same high CPU usage here:

Client:  Android 5.1

My log is shorter

[2021-03-07 23:53:51.083] [error] adb:startDeviceTracker Error: spawn adb ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

[database.db.zip](https://github.com/rivafarabi/deckboard/files/6098111/database.db.zip)

**Comment by bean5** [comment]
This looks old. Can we close it?
