### ISSUE TITLE
high CPU usage here too

### ISSUE THREAD

**Issue by medoro** [rivafarabi/deckboard#670]
Same high CPU usage here:

Client:  Android 5.1

My log is shorter

[2021-03-07 23:53:51.083] [error] adb:startDeviceTracker Error: spawn adb ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

[database.db.zip](https://github.com/rivafarabi/deckboard/files/6098111/database.db.zip)

_Originally posted by @medoro in https://github.com/rivafarabi/deckboard/issues/648#issuecomment-792369779_

**Comment by bean5** [comment]
I'm guessing this has been addressed. I'm not seeing any intense CPU action even after hours of use.
