### ISSUE TITLE
Error 'Cannot find module 'jimp''

### ISSUE THREAD

**Issue by samuelr357** [rivafarabi/deckboard#675]
error when opening deckboard v1.9.87 in linux ubuntu 20.10 running on .deb x64 regarding .appimage

A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'jimp'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.Module._resolveFilename (/opt/Deckboard/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/opt/Deckboard/resources/app.asar/dist/main/index.js:1:203232)
    at t (/opt/Deckboard/resources/app.asar/dist/main/index.js:1:279)
    at Object.<anonymous> (/opt/Deckboard/resources/app.asar/dist/main/index.js:1:198378)
    at t (/opt/Deckboard/resources/app.asar/dist/main/index.js:1:279)
    at Object.<anonymous> (/opt/Deckboard/resources/app.asar/dist/main/index.js:1:180996)

even with the jimp module installed, the error persists.

**Comment by rivafarabi** [comment]
Thanks for the feedback. This issue has been fixed in version [1.9.88](https://github.com/rivafarabi/deckboard/releases/tag/v1.9.88)
