### ISSUE TITLE
[BUG] 2.0.0 beta 2 library dependency error still occours

### ISSUE THREAD

**Issue by neosoyo** [rivafarabi/deckboard#718]
**Describe the bug**
.deb error: libnode64 is not installable. Manual installation of libnode64 allows deckboard to run but conflicts with libnode72, apt fix the conflict uninstalling deckboard and libnode64.
AppImage error: fails to load sqlite3, libnode.so.64 not found.

**To Reproduce**
```Shell
sbo@pop-os:~/Downloads$ sudo dpkg -i deckboard_2.0.0-beta.2_amd64.deb
dpkg: dependency problems prevent configuration of deckboard:
 deckboard depends on libnode64; however:
  Package libnode64 is not installed.

dpkg: error processing package deckboard (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu4) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 deckboard
sbo@pop-os:~/Downloads$ ./Deckboard-2.0.0-beta.2.AppImage 
{ appDir: '/home/sbo/deckboard', os: '/home/sbo' }
Checking for update
node-pre-gyp info This Node instance does not support builds for N-API version 6
node-pre-gyp info This Node instance does not support builds for N-API version 6
Knex: run
$ npm install sqlite3 --save
Error: libnode.so.64: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/tmp/.mount_DeckboazOX2l/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Object.<anonymous> (/tmp/.mount_DeckboazOX2l/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/tmp/.mount_DeckboazOX2l/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:2:15)
    at Object.<anonymous> (/tmp/.mount_DeckboazOX2l/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:207:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Client_SQLite3._driver (/tmp/.mount_DeckboazOX2l/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:79:12)
    at Client_SQLite3.initializeDriver (/tmp/.mount_DeckboazOX2l/resources/app.asar/node_modules/knex/lib/client.js:254:26)
[02:01:17.974] [error] ext:cleanTemp Error: ENOENT: no such file or directory, scandir '/home/sbo/deckboard/temp'
    at Object.readdirSync (fs.js:764:3)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:641:39)
    at /tmp/.mount_DeckboazOX2l/resources/app.asar/dist/main/index.js:1:68913
    at Generator.next (<anonymous>)
    at n (/tmp/.mount_DeckboazOX2l/resources/app.asar/dist/main/index.js:1:8915)
    at /tmp/.mount_DeckboazOX2l/resources/app.asar/dist/main/index.js:1:9011
    at process._tickCallback (internal/process/next_tick.js:68:7)

[02:01:17.995] [error] adb:startDeviceTracker Error: spawn adb ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:20765) UnhandledPromiseRejectionWarning: Error: spawn adb ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:20765) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:20765) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Unhandled rejection TypeError: Cannot read property 'Database' of undefined
    at /tmp/.mount_DeckboazOX2l/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:106:33
    at Promise._execute (/tmp/.mount_DeckboazOX2l/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/tmp/.mount_DeckboazOX2l/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/tmp/.mount_DeckboazOX2l/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_SQLite3.acquireRawConnection (/tmp/.mount_DeckboazOX2l/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:105:12)
    at create (/tmp/.mount_DeckboazOX2l/resources/app.asar/node_modules/knex/lib/client.js:283:23)
    at utils_1.tryPromise (/tmp/.mount_DeckboazOX2l/resources/app.asar/node_modules/tarn/lib/Pool.js:315:34)
    at Object.tryPromise (/tmp/.mount_DeckboazOX2l/resources/app.asar/node_modules/tarn/lib/utils.js:53:24)
    at Promise (/tmp/.mount_DeckboazOX2l/resources/app.asar/node_modules/tarn/lib/Pool.js:315:17)
    at new Promise (<anonymous>)
    at callbackOrPromise (/tmp/.mount_DeckboazOX2l/resources/app.asar/node_modules/tarn/lib/Pool.js:306:12)
    at Pool._create (/tmp/.mount_DeckboazOX2l/resources/app.asar/node_modules/tarn/lib/Pool.js:236:9)
    at Pool._doCreate (/tmp/.mount_DeckboazOX2l/resources/app.asar/node_modules/tarn/lib/Pool.js:208:36)
    at Pool._tryAcquireOrCreate (/tmp/.mount_DeckboazOX2l/resources/app.asar/node_modules/tarn/lib/Pool.js:159:18)
    at Pool.acquire (/tmp/.mount_DeckboazOX2l/resources/app.asar/node_modules/tarn/lib/Pool.js:85:14)
    at /tmp/.mount_DeckboazOX2l/resources/app.asar/node_modules/knex/lib/client.js:336:26
    at tryCatcher (/tmp/.mount_DeckboazOX2l/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/tmp/.mount_DeckboazOX2l/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/method.js:39:29)
    at Client_SQLite3.acquireConnection (/tmp/.mount_DeckboazOX2l/resources/app.asar/node_modules/knex/lib/client.js:335:34)
    at Runner.ensureConnection (/tmp/.mount_DeckboazOX2l/resources/app.asar/node_modules/knex/lib/runner.js:233:24)
    at Runner.run (/tmp/.mount_DeckboazOX2l/resources/app.asar/node_modules/knex/lib/runner.js:47:42)
    at Builder.Target.then (/tmp/.mount_DeckboazOX2l/resources/app.asar/node_modules/knex/lib/interface.js:39:43)
    at e.default.connectDatabase (/tmp/.mount_DeckboazOX2l/resources/app.asar/dist/main/index.js:1:1504128)
    at c.default.exists.B (/tmp/.mount_DeckboazOX2l/resources/app.asar/dist/main/index.js:1:1510396)
    at suppressedCallback (fs.js:200:5)
    at FSReqWrap.oncomplete (fs.js:141:20)
```
Pop!_OS 20.10
nodejs v12.18.2
Tried symbolic link to libnode.so.72 and libnode.so and AppImage gives:
```
{ appDir: '/home/sbo/deckboard', os: '/home/sbo' }
Checking for update
node-pre-gyp info This Node instance does not support builds for N-API version 6
node-pre-gyp info This Node instance does not support builds for N-API version 6
Segmentation fault (core dumped)
```
there is no log file in .config/deckboard/ folder using symbolic links.

**Comment by neosoyo** [comment]
it seems to be related with a[ nodejs bug.
](https://salsa.debian.org/js-team/nodejs/-/commit/5d56e34311168c4cc7eb6118154aece52bc8dae2)

**Comment by luccacondratiuk** [comment]
In Ubuntu 20.04, I was able to install it manually - [libnode64](https://www.ubuntuupdates.org/package/core/focal/universe/base/libnode64), an then deckboard ran without issues... but in arch linux, I'm getting the same error, and I didn't found any solutions yet

**Comment by eribertomota** [comment]
In Debian 11 and derivative distros like Ubuntu, the  libnode64 was superseded by libnode72 and libicu66 is now libicu67.

I opened #798 asking for a change in packaging. There is a workaround:

```
# apt install libnode72 libicu67
# ar -x deckboard_1.9.99_amd64.deb
# tar -xvf data.tar.xz
# cp -a opt/* /opt
# cp -a usr/* /usr
```

**Comment by Donzii** [comment]
Hi, same here:
Workaround did work, but its to complicated for fresh Lin* Users ;o)

Linux Mint 21 x86_64
Kernel: 6.0.7

libnode72 libicu70 are installed, but deckboard want libnode64 & libicu66
Want to switch from Streamdeck to Deckboard.
