### ISSUE TITLE
[BUG] Spotify control doesn't work

### ISSUE THREAD

**Issue by LucasPalluel** [rivafarabi/deckboard#774]
**Describe the bug**
When I try to pause or play music on spotify, or increase/decrease volume or anything, nothing happens. I have premium spotify and it's just don't work. Can I do anything to fix that ?

**To Reproduce**
1. Go to parameters
2. Log on spotify
3. Create control buttons for spotify and try it
4. Nothing happens

**Expected behavior**
Controls my spotify

**Server App (please complete the following information):**
 - OS: Windows 10
 - Version 21H1

**Client App (please complete the following information):**
 - OS: EMUI 4.0
 - Version 6.0.1

**Additional context**
I use deckboard PRO

**Comment by schumi2004** [comment]
Same issue here. I see the following errors in log file

[2021-09-30 11:40:04.511] [error] spotify:runPlaybackControl WebapiPlayerError: An error occurred while communicating with Spotify's Web API.
Details: Player command failed: Restriction violated UNKNOWN.

**Comment by MajorMadeV1** [comment]
I do not work for rivafarabi and I don't really understand code or even logs but since I ran into a similar problem: My errors logged in the file (located at C:\Users\{USER}\AppData\Roaming\Deckboard) all pointed towards me not having Spotify premium.
Please check if you have Spotify premium. If you don't have it, some functionality might not be given (basically all Spotify controls won't work).

**Comment by schumi2004** [comment]
@MajorMadeV1 in my case I do have Spotify premium, family plan.

**Comment by Fr4nckyDumpi** [comment]
For my part, I use version 1.9.99 and Spotify Prenium, I have access to commands such as :

- Like Song
- Play a selected playlist

But I can't use other buttons like :

- Play / Stop
- Next / Previous music
- Increase sound / Decrease sound

```
[2021-12-19 01:06:17.876] [error] spotify:runPlaybackControl WebapiPlayerError: An error occurred while communicating with Spotify's Web API.
Details: Player command failed: Restriction violated UNKNOWN.
    at _toError (C:\Program Files\Deckboard\resources\app.asar\node_modules\spotify-web-api-node\src\http-manager.js:35:12)
    at C:\Program Files\Deckboard\resources\app.asar\node_modules\spotify-web-api-node\src\http-manager.js:71:25
    at Request.fn [as callback] (C:\Program Files\Deckboard\resources\app.asar\node_modules\superagent\src\node\index.js:902:3)
    at callback (C:\Program Files\Deckboard\resources\app.asar\node_modules\superagent\src\node\index.js:1130:18)
    at IncomingMessage.fn (C:\Program Files\Deckboard\resources\app.asar\node_modules\superagent\src\node\parsers\json.js:19:7)
    at Stream.emit (events.js:182:13)
    at Unzip.emit (C:\Program Files\Deckboard\resources\app.asar\node_modules\superagent\src\node\unzip.js:54:12)
    at Unzip.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
One idea ?

**Comment by Damaskinus** [comment]
Same here.  I Have Deckboard PRO, Spotify Premium and started to use it today, and I can't pause or play, and next or previous

**Comment by rivafarabi** [comment]
1. After I checked this issue, it seems the playback function won't start if the Spotify itself does not have an active device. User can activate the device by playing any track on Spotify.

2. The `Restriction violated UNKNOWN` error seems to be recurring issue on Spotify Web API, but commonly caused by repeatedly pressing the play/pause button.

P.S. Version 2.0.1 includes the system notification to show these error messages.

**Comment by redredpumpkin** [comment]
Hi. I am having the same issue right now with spotify. I have spotify premium and I tried playing songs first via the spotify desktop version then used the deckboard button and it won't work now.

It used to work but it only plays for my other devices where spotify is logged in like my laptop.. I have 3 devices where my spotify is logged in

phone
desktop pc
laptop

and when i first set up the button to interact/control playback spotify, the spotify window on my desktop would show that the song is playing on my laptop downstairs... even if multiple times I selected my desktop pc. Can anyone help? Thank you~ I really appreciate it.

**Comment by TheGalitube** [comment]
@redredpumpkin 

You have to close both spotify and Deckboard. denn open Deckboard, and when deckboard is connected to your Device, then you can open Spotify again and it should work.
