### ISSUE TITLE
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by abobowicz** [rivafarabi/deckboard#965]
I've updated my snap installation form 2.0.x (I don't remember the exact version) to 2.1.1 and now the app does not start. Before that it was fine.
When I'm trying to start it from the console I'm getting a few errors, first one is in the bug report title. The whole log beloved

Os is Manjaro 22.0.4 with Gnome shell
```
Gtk-Message: 23:43:34.152: Failed to load module "xapp-gtk3-module"
{ appDir: '/home/saint/snap/deckboard/11/deckboard',
  os: '/home/saint/snap/deckboard/11' }
Checking for update
Knex: run
$ npm install sqlite3 --save
Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /run/user/1000/snap.deckboard/.org.chromium.Chromium.QNnqGG)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/snap/deckboard/11/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Object.<anonymous> (/snap/deckboard/11/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/snap/deckboard/11/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:2:15)
    at Object.<anonymous> (/snap/deckboard/11/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:207:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Client_SQLite3._driver (/snap/deckboard/11/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:79:12)
    at Client_SQLite3.initializeDriver (/snap/deckboard/11/resources/app.asar/node_modules/knex/lib/client.js:254:26)
event
[23:43:35.133] [error] ext:cleanTemp Error: ENOENT: no such file or directory, scandir '/home/saint/snap/deckboard/11/deckboard/temp'
    at Object.readdirSync (fs.js:764:3)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:641:39)
    at /snap/deckboard/11/resources/app.asar/dist/main/index.js:1:24736
    at Generator.next (<anonymous>)
    at o (/snap/deckboard/11/resources/app.asar/dist/main/index.js:1:6701)
    at /snap/deckboard/11/resources/app.asar/dist/main/index.js:1:6797
    at process._tickCallback (internal/process/next_tick.js:68:7)

Error: Error: ENOENT: no such file or directory, open '/snap/deckboard/11/resources/app-update.yml'
(node:33043) UnhandledPromiseRejectionWarning: Error: Object has been destroyed
    at AppImageUpdater.i.autoUpdater.on.e (/snap/deckboard/11/resources/app.asar/dist/main/index.js:1:48102)
    at AppImageUpdater.emit (events.js:187:15)
    at checkForUpdatesPromise.doCheckForUpdates.then.catch.e (/snap/deckboard/11/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:354:12)
(node:33043) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:33043) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[23:43:35.155] [error] adb:startDeviceTracker Error: spawn adb ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:33043) UnhandledPromiseRejectionWarning: Error: spawn adb ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:33043) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
Unhandled rejection TypeError: Cannot read property 'Database' of undefined
    at /snap/deckboard/11/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:106:33
    at Promise._execute (/snap/deckboard/11/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/snap/deckboard/11/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/snap/deckboard/11/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/promise.js:103:10)
    at Client_SQLite3.acquireRawConnection (/snap/deckboard/11/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:105:12)
    at create (/snap/deckboard/11/resources/app.asar/node_modules/knex/lib/client.js:283:23)
    at utils_1.tryPromise (/snap/deckboard/11/resources/app.asar/node_modules/tarn/lib/Pool.js:315:34)
    at Object.tryPromise (/snap/deckboard/11/resources/app.asar/node_modules/tarn/lib/utils.js:53:24)
    at Promise (/snap/deckboard/11/resources/app.asar/node_modules/tarn/lib/Pool.js:315:17)
    at new Promise (<anonymous>)
    at callbackOrPromise (/snap/deckboard/11/resources/app.asar/node_modules/tarn/lib/Pool.js:306:12)
    at Pool._create (/snap/deckboard/11/resources/app.asar/node_modules/tarn/lib/Pool.js:236:9)
    at Pool._doCreate (/snap/deckboard/11/resources/app.asar/node_modules/tarn/lib/Pool.js:208:36)
    at Pool._tryAcquireOrCreate (/snap/deckboard/11/resources/app.asar/node_modules/tarn/lib/Pool.js:159:18)
    at Pool.acquire (/snap/deckboard/11/resources/app.asar/node_modules/tarn/lib/Pool.js:85:14)
    at /snap/deckboard/11/resources/app.asar/node_modules/knex/lib/client.js:336:26
    at tryCatcher (/snap/deckboard/11/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/snap/deckboard/11/resources/app.asar/node_modules/knex/node_modules/bluebird/js/release/method.js:39:29)
    at Client_SQLite3.acquireConnection (/snap/deckboard/11/resources/app.asar/node_modules/knex/lib/client.js:335:34)
    at Runner.ensureConnection (/snap/deckboard/11/resources/app.asar/node_modules/knex/lib/runner.js:233:24)
    at Runner.run (/snap/deckboard/11/resources/app.asar/node_modules/knex/lib/runner.js:47:42)
    at Builder.Target.then (/snap/deckboard/11/resources/app.asar/node_modules/knex/lib/interface.js:39:43)
    at t.default.connectDatabase (/snap/deckboard/11/resources/app.asar/dist/main/index.js:1:169811)
    at u.default.exists.e (/snap/deckboard/11/resources/app.asar/dist/main/index.js:1:177284)
    at suppressedCallback (fs.js:200:5)
    at FSReqWrap.oncomplete (fs.js:141:20)
```

**Comment by guilhem** [comment]
same here with 2.1.2 on ubuntu 23.04

**Comment by rivafarabi** [comment]
Deckboard version 3.0.0+ should fix this issue. Closing this
