### ISSUE TITLE
[BUG] Deckboard Snap won't start on Debian 11

### ISSUE THREAD

**Issue by marco-silvestri** [rivafarabi/deckboard#978]
**Describe the bug**
Hi, I have installed the latest Deckboard through the snap store, under Debian 11. When I start it, I get  a NodeJS error.

**To Reproduce**
1. Install with `sudo snap install deckboard`
2. Start with `snap run deckboard`

**Expected behavior**
I am expecting the app to start

**Screenshots**
`➜  Downloads snap run deckboard 
{ appDir: '/home/marco/snap/deckboard/12/deckboard',
  os: '/home/marco/snap/deckboard/12' }
Checking for update
[14:53:33.337] [error] db:28 /snap/deckboard/12/resources/database.db is not found.
Error: Error: ENOENT: no such file or directory, open '/snap/deckboard/12/resources/app-update.yml'
(node:86937) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/snap/deckboard/12/resources/app-update.yml'
(node:86937) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:86937) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Knex: run
$ npm install sqlite3 --save
Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /run/user/1000/snap.deckboard/.org.chromium.Chromium.4DRQK7)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/snap/deckboard/12/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Object.<anonymous> (/snap/deckboard/12/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/snap/deckboard/12/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:2:15)
    at Object.<anonymous> (/snap/deckboard/12/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:207:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Client_SQLite3._driver (/snap/deckboard/12/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:79:12)
    at Client_SQLite3.initializeDriver (/snap/deckboard/12/resources/app.asar/node_modules/knex/lib/client.js:254:26)
event
[14:53:33.478] [error] ext:cleanTemp Error: ENOENT: no such file or directory, scandir '/home/marco/snap/deckboard/12/deckboard/temp'
    at Object.readdirSync (fs.js:764:3)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:641:39)
    at /snap/deckboard/12/resources/app.asar/dist/main/index.js:1:24736
    at Generator.next (<anonymous>)
    at o (/snap/deckboard/12/resources/app.asar/dist/main/index.js:1:6701)
    at /snap/deckboard/12/resources/app.asar/dist/main/index.js:1:6797
    at process._tickCallback (internal/process/next_tick.js:68:7)

[14:53:33.491] [error] adb:startDeviceTracker Error: spawn adb ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:86937) UnhandledPromiseRejectionWarning: Error: spawn adb ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:86937) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
`

**Server App (please complete the following information):**
 - OS: Debian
 - Version 11

**Comment by samuk10** [comment]
same here
