### ISSUE TITLE
[BUG] Snap Version doesn't launch on Fedora Linux

### ISSUE THREAD

**Issue by Arbee4ever** [rivafarabi/deckboard#984]
**Describe the bug**
When I install it using snap, it doesn't launch at all and when I try it in the Terminal I get this error: 
```npm install sqlite3 --save
Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /run/user/1000/snap.deckboard/.org.chromium.Chromium.1gC4TD)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/snap/deckboard/13/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Object.<anonymous> (/snap/deckboard/13/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/snap/deckboard/13/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:2:15)
    at Object.<anonymous> (/snap/deckboard/13/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:207:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Client_SQLite3._driver (/snap/deckboard/13/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:79:12)
    at Client_SQLite3.initializeDriver (/snap/deckboard/13/resources/app.asar/node_modules/knex/lib/client.js:254:26)
Gtk-Message: 19:02:02.035: GtkDialog mapped without a transient parent. This is discouraged.
[19:02:03.478] [error] ext:cleanTemp Error: ENOENT: no such file or directory, scandir '/home/arbee/snap/deckboard/13/deckboard/temp'
    at Object.readdirSync (fs.js:764:3)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:641:39)
    at /snap/deckboard/13/resources/app.asar/dist/main/index.js:1:21961
    at Generator.next (<anonymous>)
    at o (/snap/deckboard/13/resources/app.asar/dist/main/index.js:1:6701)
    at /snap/deckboard/13/resources/app.asar/dist/main/index.js:1:6797
    at process._tickCallback (internal/process/next_tick.js:68:7)

[19:02:03.504] [error] adb:startDeviceTracker Error: spawn adb ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:34631) UnhandledPromiseRejectionWarning: Error: spawn adb ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:34631) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**To Reproduce**
1. Install on Fedora
2. Run `deckboard` in Terminal

**Expected behavior**
It should Launch without errors.

**Server App (please complete the following information):**
 - OS: [Fedora 38]
 - Version [2.1.3]

**Client App (please complete the following information):**
 - OS: [Android 13]
 - Version [2.1.0]

**Required files**
- [database.db.zip](https://github.com/rivafarabi/deckboard/files/11415573/database.db.zip)
- log.log (Where is it on Linux?)

**Comment by samuk10** [comment]
same here, ubuntu 23.04

**Comment by ben3291** [comment]
meme chose sur pop-os 22.04 même le deb et casser
