### ISSUE TITLE
White Screen When Trying To Log Into Twitter

### ISSUE THREAD

**Issue by dtronicsuk** [rivafarabi/deckboard#988]
Hey

Im having an issue where im having issues logging into twitter.

I click the login button and all i get is a white window. The login window for spotify opens fine as does twitch but twitter doesnt open correctly and instead just shows a white window.

Im running Linux, Manjaro Arch Linux with the Plasma 5 DE

**Comment by arkanoego** [comment]
I have the same but with login into spotify

Fresh win10 22H2,

**Comment by florian-berger** [comment]
I have the same issue as dtronicsuk with the Twitter authentication. I think Twitter has changed something in their API.

Log:
```
[2023-06-17 00:19:09.169] [error] twitter:auth Error: 401 -  : {"errors":[{"code":32,"message":"Could not authenticate you."}]}
    at IncomingMessage.<anonymous> (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:1:117361)
    at IncomingMessage.emit (events.js:182:13)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)```

**Comment by rivafarabi** [comment]
New authentication method has just been updated in [v2.1.4](https://github.com/rivafarabi/deckboard/releases/tag/v2.1.4)
